# Generated by Django 4.0.8 on 2022-12-31 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221118_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountsValidationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(default=datetime.datetime(2022, 12, 31, 18, 48, 41, 742643))),
                ('validation_code', models.BigIntegerField(default=4132124404728636264)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
