# Generated by Django 4.0.8 on 2023-01-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 4, 57, 7, 58999)),
        ),
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='validation_code',
            field=models.BigIntegerField(default=8804007272747132137),
        ),
    ]
