# Generated by Django 4.0.8 on 2023-01-01 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountsvalidationmodel_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 22, 17, 4, 734176)),
        ),
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='validation_code',
            field=models.BigIntegerField(default=2824382419390198609),
        ),
    ]
