# Generated by Django 4.0.8 on 2023-01-01 22:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountsvalidationmodel_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='expiration',
            field=models.DateTimeField(default=accounts.models.new_exp_date),
        ),
        migrations.AlterField(
            model_name='accountsvalidationmodel',
            name='validation_code',
            field=models.BigIntegerField(default=accounts.models.new_code),
        ),
    ]
