# Generated by Django 4.0.7 on 2022-10-29 19:06

from django.db import migrations

def populate_time_frequencies(apps, schema_editor):
    values = ['Daily', 'Weekly', 'Monthly', 'Yearly']
    TimeFrequenciesModel = apps.get_model('budget', 'TimeFrequenciesModel')

    for value in values:
        timeFrequenciesModel = TimeFrequenciesModel()
        timeFrequenciesModel.frequency = value
        timeFrequenciesModel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_timefrequenciesmodel_repeatingtransactionsmodel'),
    ]

    operations = [
        migrations.RunPython(populate_time_frequencies),
    ]
